import React from 'react'
import Head from 'next/head';
import { Templates } from '../templates/Templates'
import Button from '../atoms/Button';

const FS = () => {
  return (
    <>
         <Head>
        <title>Feasebility Study - PT. Bumi Nusantara Hijau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Templates>
        <main className="bg-[#F8F9FA] py-10 pt-16 md:px-32" >
        <div>
            <h1 className="md:text-2xl font-bold text-xl mb-2" >Feasebility Study (Studi Kelayakan) </h1>
            <p>Adalah teknik analisis yang digunakan untuk menilai kualitas dari faktor-faktor sebuah proyek, yang meliputi proyek industri/bangunan gedung, pariwisata, perkantoran, usaha & bisnis sektor lainnya.</p>
            <h2 className="md:text-xl text-md mt-10 font-bold" >Hasil keluaran Feasebility</h2>
            <ul className="mt-2" >
                <li>1. Dokumen KA-ANDAL</li>
                <li>2. Dokumen ANDAL, RKL & RPL</li>
                <li>3. Persetujuan lingkungan dari Dinas Lingkungan Hidup</li>
                <li>4. Surat keterangan kelayakan lingkungan (SKKL/PKPLH)</li>
            </ul>
            <h2 className="md:text-xl text-md mt-10 font-bold" >Persyaratan</h2>
            <ul className="mt-2" >
                <li>1. Foto copy akte pendirian perusahaan dan perubahannya</li>
                <li>2. Foto copy sertifikat tanah/ surat tanah</li>
                <li>3. Foto copy TKPRD dari dinas tata ruang</li>
                <li>4. Foto copy/soft copy master plan dari dinas tata ruang</li>
                <li>5. Gambar arsitektur dan struktur (soft copy/hard copy)</li>
                <li>6. Buku laporan perencanaan (M/E)</li>
                <li>7. Buku penyelidikan tanah (soil investigation)</li>
                <li>8. Gambar perspektif tampak bangunan (warna)</li>
                <li>9. Jadwal pelaksanaan konstruksi/pembangunan</li>
                <li>10. Struktur organisasi proyek</li>
                <li>11. Persetujuan teknis baku mutu air limbah (pertek air limbah)</li>
                <li>12. Persetujuan teknis limbah B3 (Pertek B3)</li>
                <li>13. Persetujuan teknis baku mutu emisi (Pertek emisi)</li>
                <li>14. Persetujuan Teknis Andalalin (Analisis dampak lalu lintas)</li>
            </ul>
            {/* <Button title="Konsultasi Sekarang" style="bg-secondary text-white mt-5 px-5 py-3 rounded-lg" /> */}
        </div>
      </main>
        </Templates>
    </>
  )
}

export default FS