import Head from 'next/head'
import About from '../components/About'
import Advantages from '../components/Advantages'
import Services from '../components/Services'
import Partner from '../components/Partner'
import { Templates } from '../templates/Templates'

export default function Home() {
  return (
    <>
      <Head>
        <title>Beranda - PT. Bumi Nusantara Hijau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Templates>
      <main className="bg-[#F8F9FA]" >
        <About/>
        <Advantages/>
        <Services/>
        <Partner/>
      </main>
    </Templates>
    </>
  )}
