import React from 'react'
import { Templates } from '../templates/Templates'
import Head from "next/head"
import {BsWhatsapp} from "react-icons/bs"
import {AiOutlinePhone} from "react-icons/ai"
import {BiEnvelope} from "react-icons/bi"
import Advantage from './../atoms/Advantage';
import Form from "../components/Form";

const Kontak = () => {
  return (
    <>
    <Head>
        <title>Kontak - PT. Bumi Nusantara Hijau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Templates>
        <main className='bg-[#F8F9FA]' >
            <div className="px-10 py-20 flex flex-col md:flex-row justify-between " >
            <Advantage
          Icon={<BsWhatsapp className="mt-1" size={35} />}
          title="+6282253654721"
          subtitle="Kamu bisa hubungi kami via WhatsApp"
        />
          <Advantage
        Icon={<BiEnvelope className="mt-1" size={35} />}
        title="buminusantarahijau@mail.com"
        subtitle="Kamu bisa hubungi via gmail yang akan terhubung dengan admin kami"
      />
            <Advantage
          Icon={<AiOutlinePhone className="mt-1" size={40} />}
          title="+6282253654721"
          subtitle="Kamu bisa hubungi kami via Telephone"
        />
            </div>
            <Form/>
        </main>
    </Templates>
    </>
  )
}

export default Kontak